services:
  edge:
    build: .
    ports:
      - "8000:8000"

  remote:
    build: .
    ports:
      - "8001:8000"
    cap_add:
      - NET_ADMIN
    command: sh -c "tc qdisc add dev eth0 root netem delay 100ms && fastapi run main.py --host 0.0.0.0 --port 8000"
